---
title: "Map preparation for Homework #1"
author: "Haley Chinander"
output:
  html_document:
    df_print: paged
---

## Load libraries

```{r}

library(ggplot2)
library(scales)
library(leaflet)
library(sf)
```



## Link data from github

```{r}
rm(list = ls())

cambridgeLink="https://github.com/SpatialDataAssignments/SDA_Homework2/raw/refs/heads/main/cambridge_grid10_idw.gpkg"

homeLink = "https://github.com/SpatialDataAssignments/SDA_Homework2/raw/refs/heads/main/myEstats.gpkg"

cambridge <- st_read(cambridgeLink)

estate <- st_read(homeLink)

```


## Checking CRS

```{r}
st_crs(europe)$epsg
```

# Create the base map

```{r}

ggplot() +
  geom_sf(data = cambridge, aes(fill = IDW_10)) + # Plot the grid with IDW results
  scale_fill_viridis_c() + # Use a color scale for the interpolated prices
  geom_sf(data = estate, color = "red", size = 3) + # Plot your estate point
  labs(title = "Interpolated AirBNB Prices and My Estate Location", fill = "IDW Price") +
  theme_minimal() 




ggplot() + theme_light() +
  #call map
  geom_sf(data = europe) + 
  # adjust datum 
  coord_sf(datum = st_crs(europe)) + 
  # custom X and Y axes
  scale_x_continuous(labels = label_number(scale = 1/1000, suffix = " km")) +
  scale_y_continuous(labels = label_number(scale = 1/1000, suffix = " km")) +
  labs(x = "Easting", y = "Northing") #labels
```

# Map One: DDM Static

```{r}
plot1_a=ggplot() + theme_light() +
  #base
  geom_sf(data = europe,fill="white",color="grey80") +
  # layer
  geom_sf(data=europeMobi_ddm,
          alpha=0.1,#transparency
          shape=20,
          size=0.5,
          color="darkblue")+
  coord_sf(datum = st_crs(europe)) + 
  scale_x_continuous(labels = label_number(scale = 1/1000, suffix = " km")) +
  scale_y_continuous(labels = label_number(scale = 1/1000, suffix = " km")) +
  labs(title= "Mobile phone subscribers by country", x = "Easting", y = "Northing") #labels

plot1_a

```

# Map Two: DDM Interactive

```{r}

# CRS for leaflet
ddm_4326 <- st_transform(europeMobi_ddm, crs = 4326)

plot1_b=leaflet() %>%
  addProviderTiles(providers$CartoDB.Positron)  %>%  # names in english
  addCircleMarkers(data = ddm_4326,
                   color="darkblue",
                   stroke=0,
                   radius = 0.01,
                   opacity = 0.1)
plot1_b
```

# Map Three: PSM Static

```{r}
plot2_a=ggplot() + theme_light() +
  #base
  geom_sf(data = europe,fill="white",color="grey80") +
  # layer
  geom_sf(data=europeMobi_psm,
          shape=20,
          aes(size=mobiles/1000,color=factor(mobiles_outlier)))+
  scale_size_area(
    name = "Mobile phone subscribers (x1,000)", # Name for the legend
    max_size = 10) +       # This defines the maximum *radius*
  guides(color="none") + 
  
  coord_sf(datum = st_crs(europe)) + 
  # custom X and Y axes
  scale_x_continuous(labels = label_number(scale = 1/1000, suffix = " km")) +
  scale_y_continuous(labels = label_number(scale = 1/1000, suffix = " km")) +
  labs(title = "Mobile phone subscribers by country",x = "Easting", y = "Northing") 

plot2_a  

```

# Map Four: PSM Interactive

```{r}

# CRS for leaflet
psm_4326 <- st_transform(europeMobi_psm, crs = 4326)


plot2_b=leaflet() %>%
  addProviderTiles(providers$CartoDB.Positron)  %>%  
  addCircleMarkers(data = psm_4326,
                   label = ~Country,
                   radius = ~size)
plot2_b

```

# Map Five: Choro Static

```{r}
plot3_a=ggplot() + theme_light() +
  geom_sf(data=europe,
          aes(fill=mobiles_pop_FJ5_cat))+
  coord_sf(datum = st_crs(europe)) +
  scale_fill_brewer(direction = 1,palette = 'Spectral') + 
  scale_x_continuous(labels = label_number(scale = 1/1000, suffix = " km")) +
  scale_y_continuous(labels = label_number(scale = 1/1000, suffix = " km")) +
  labs(title = "Mobile phone subscribers as a percent of country population",x = "Easting", y = "Northing",fill="Mobile phone uptake")
  
plot3_a
  
```

# Map Six: Choro Interactive

```{r}
choro_4326 <- st_transform(europe, crs = 4326)

choro_4326$mobiles_pop_FJ5_cat=ordered(choro_4326$mobiles_pop_FJ5_cat)
pal <- colorFactor(palette = "Spectral",
                   domain = choro_4326$mobiles_pop_FJ5_cat,
                   ordered = T,
                   reverse = F)

leaflet() %>%
  addProviderTiles(providers$CartoDB.Positron)  %>% 
  addPolygons(
    data = choro_4326,
    fillColor = ~pal(mobiles_pop_FJ5_cat),
    fillOpacity = 0.7,
    color = "white",
    weight = 1,
    opacity = 1
    ) %>%
  addLegend(
    pal = pal,
    values = choro_4326$mobiles_pop_FJ5_cat,
    )
```

#Calculate Europe Center

```{r}

europe_center <- st_bbox(choro_4326) %>% 
  as.vector() %>% 
  {c(mean(c(.[1], .[3])), mean(c(.[2], .[4])))}  # Calculate center coordinates


plot3_b=leaflet() %>%
  addProviderTiles(providers$CartoDB.Positron)  %>% 
addPolygons(
    data = choro_4326,
    fillColor = ~pal(mobiles_pop_FJ5_cat),
    fillOpacity = 0.7,
    color = "white",
    weight = 1,
    opacity = 1,
    label = lapply(
      paste("<strong>", choro_4326$Country, "</strong><br>",
            "Density: ", choro_4326$mobiles_pop),
      htmltools::HTML
    )
  ) %>%
  addLegend(
    pal = pal,
    values = choro_4326$mobiles_pop_FJ5_cat,
    opacity = 0.7,
    title = "Mobile phone subscriptions as percent of population",
    position = "bottomright"
  )%>%
  addEasyButton(
    easyButton(
      icon = "fa-home", 
      title = "Reset to Europe View",
      onClick = JS(sprintf("function(btn, map){ map.setView([%f, %f], 3); }", 
                          europe_center[2], europe_center[1]))
    )
  )
plot3_b
```

# Save plots for dashboard

```{r}
saveRDS(plot1_a,file = "plot1_a.rds")
saveRDS(plot1_b,file = "plot1_b.rds")
saveRDS(plot2_a,file = "plot2_a.rds")
saveRDS(plot2_b,file = "plot2_b.rds")
saveRDS(plot3_a,file = "plot3_a.rds")
saveRDS(plot3_b,file = "plot3_b.rds")
```
